### ISSUE TITLE
[Insight] No license specified

### ISSUE THREAD

**Issue by LewisW** [vivait/TenantBundle#12]
**[in composer.json](https://github.com/LewisW/TenantBundle/blob/master/composer.json#L0)**

> No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.

---

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/c46fdf9a-2d7d-469f-876b-a85dfc717365/analyses/2)_

**Comment by kieljohn** [comment]
Updated license to MIT
